export const MOCK_CATALOG = [
  { id: 1, name: 'Apple', category: 'Produce', price: 30 },
  { id: 2, name: 'Banana', category: 'Produce', price: 10 },
  { id: 3, name: 'Orange', category: 'Produce', price: 20 },
  { id: 4, name: 'Mango', category: 'Produce', price: 50 },
  { id: 5, name: 'Grapes', category: 'Produce', price: 80 },
  { id: 6, name: 'Watermelon', category: 'Produce', price: 150 },
  { id: 7, name: 'Papaya', category: 'Produce', price: 60 },
  { id: 8, name: 'Pineapple', category: 'Produce', price: 90 },
  { id: 9, name: 'Pomegranate', category: 'Produce', price: 120 },
  { id: 10, name: 'Guava', category: 'Produce', price: 40 },
  { id: 11, name: 'Tomato', category: 'Produce', price: 30 },
  { id: 12, name: 'Potato', category: 'Produce', price: 25 },
  { id: 13, name: 'Onion', category: 'Produce', price: 35 },
  { id: 14, name: 'Garlic', category: 'Produce', price: 100 },
  { id: 15, name: 'Ginger', category: 'Produce', price: 80 },
  { id: 16, name: 'Carrot', category: 'Produce', price: 40 },
  { id: 17, name: 'Spinach', category: 'Produce', price: 20 },
  { id: 18, name: 'Broccoli', category: 'Produce', price: 150 },
  { id: 19, name: 'Cabbage', category: 'Produce', price: 30 },
  { id: 20, name: 'Capsicum', category: 'Produce', price: 50 },
  
  { id: 21, name: 'Milk', category: 'Dairy', price: 65 },
  { id: 22, name: 'Cheese', category: 'Dairy', price: 120 },
  { id: 23, name: 'Yogurt', category: 'Dairy', price: 45 },
  { id: 24, name: 'Butter', category: 'Dairy', price: 55 },
  { id: 25, name: 'Paneer', category: 'Dairy', price: 90 },
  { id: 26, name: 'Cream', category: 'Dairy', price: 70 },
  { id: 27, name: 'Oat Milk', category: 'Dairy', price: 250 },
  { id: 28, name: 'Almond Milk', category: 'Dairy', price: 300 },
  { id: 29, name: 'Ghee', category: 'Dairy', price: 550 },
  { id: 30, name: 'Ice Cream', category: 'Dairy', price: 150 },
  
  { id: 31, name: 'Bread', category: 'Bakery', price: 40 },
  { id: 32, name: 'Bagel', category: 'Bakery', price: 60 },
  { id: 33, name: 'Muffin', category: 'Bakery', price: 80 },
  { id: 34, name: 'Cake', category: 'Bakery', price: 450 },
  { id: 35, name: 'Croissant', category: 'Bakery', price: 90 },
  { id: 36, name: 'Buns', category: 'Bakery', price: 35 },
  { id: 37, name: 'Pita', category: 'Bakery', price: 50 },
  { id: 38, name: 'Tortilla', category: 'Bakery', price: 120 },
  { id: 39, name: 'Donut', category: 'Bakery', price: 60 },
  { id: 40, name: 'Brownie', category: 'Bakery', price: 75 },
  
  { id: 41, name: 'Basmati Rice', category: 'Pantry', price: 150 },
  { id: 42, name: 'Pasta', category: 'Pantry', price: 80 },
  { id: 43, name: 'Pasta Sauce', category: 'Pantry', price: 120 },
  { id: 44, name: 'Cereal', category: 'Pantry', price: 200 },
  { id: 45, name: 'Sugar', category: 'Pantry', price: 45 },
  { id: 46, name: 'Flour', category: 'Pantry', price: 50 },
  { id: 47, name: 'Olive Oil', category: 'Pantry', price: 650 },
  { id: 48, name: 'Salt', category: 'Pantry', price: 25 },
  { id: 49, name: 'Pepper', category: 'Pantry', price: 90 },
  { id: 50, name: 'Honey', category: 'Pantry', price: 220 },
  { id: 51, name: 'Jam', category: 'Pantry', price: 130 },
  { id: 52, name: 'Peanut Butter', category: 'Pantry', price: 210 },
  { id: 53, name: 'Ketchup', category: 'Pantry', price: 110 },
  { id: 54, name: 'Mayonnaise', category: 'Pantry', price: 140 },
  { id: 55, name: 'Eggs', category: 'Pantry', price: 80 },
  
  { id: 56, name: 'Chips', category: 'Snacks', price: 20 },
  { id: 57, name: 'Cookies', category: 'Snacks', price: 30 },
  { id: 58, name: 'Almonds', category: 'Snacks', price: 800 },
  { id: 59, name: 'Popcorn', category: 'Snacks', price: 50 },
  { id: 60, name: 'Chocolate', category: 'Snacks', price: 100 },
  { id: 61, name: 'Nachos', category: 'Snacks', price: 85 },
  { id: 62, name: 'Salsa', category: 'Snacks', price: 150 },
  { id: 63, name: 'Trail Mix', category: 'Snacks', price: 350 },
  { id: 64, name: 'Granola Bar', category: 'Snacks', price: 40 },
  { id: 65, name: 'Cashews', category: 'Snacks', price: 950 },
  
  { id: 66, name: 'Water', category: 'Drinks', price: 20 },
  { id: 67, name: 'Juice', category: 'Drinks', price: 110 },
  { id: 68, name: 'Soda', category: 'Drinks', price: 40 },
  { id: 69, name: 'Coffee', category: 'Drinks', price: 250 },
  { id: 70, name: 'Tea', category: 'Drinks', price: 180 },
  { id: 71, name: 'Green Tea', category: 'Drinks', price: 220 },
  { id: 72, name: 'Coconut Water', category: 'Drinks', price: 60 },
  { id: 73, name: 'Energy Drink', category: 'Drinks', price: 110 },
  { id: 74, name: 'Cold Drink', category: 'Drinks', price: 40 },
  { id: 75, name: 'Sparkling Water', category: 'Drinks', price: 80 },
];
